# Generated by Django 4.1.6 on 2023-02-23 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timeposted', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='', max_length=12, null=True)),
                ('city', models.CharField(default='', max_length=30, null=True)),
                ('state', models.CharField(default='', max_length=30, null=True)),
                ('country', models.CharField(default='', max_length=30, null=True)),
                ('address', models.CharField(default='', max_length=400, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timeposted', models.TimeField()),
                ('commentwhereposted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_app.comment')),
                ('userwhoposted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_app.useraccount')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('timeposted', models.TimeField()),
                ('title', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('desc', models.TextField(null=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_app.useraccount')),
            ],
        ),
        migrations.CreateModel(
            name='OTPStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otphere', models.CharField(max_length=6)),
                ('timecreation', models.TimeField()),
                ('timevalid', models.TimeField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_app.useraccount')),
            ],
        ),
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_app.useraccount')),
                ('userfollowed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='postedwhere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_app.post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='userwhoposted',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_app.useraccount'),
        ),
    ]
