# Generated by Django 4.1.6 on 2023-05-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_remove_post_id_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blogbg',
            field=models.ImageField(default='working', upload_to='images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='', max_length=80, primary_key=True, serialize=False),
        ),
    ]
