# Generated by Django 4.1.6 on 2023-05-14 19:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_post_blogbg_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='timeposted',
            field=models.TimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
